package com.dashboardnotice.model;

import java.util.List;

public class DashboardNoticeService {
	
	private DashboardNoticeDAOInterface dao;

	public DashboardNoticeService() {
		dao = new DashboardNoticeJDBCDAO();
	}

	public DashboardNoticeVO addDashboardNotice(
					Integer dashboardNoticeType, String dashboardNoticeText) {
		
		DashboardNoticeVO vo = new DashboardNoticeVO();
		vo.setDashboardNoticeType(dashboardNoticeType);
		vo.setDashboardNoticeText(dashboardNoticeText);
		
		int autoGeneratedKey = dao.insert(vo);
		vo = dao.getOneByID(autoGeneratedKey);
		
		return vo;
	}
	
	public DashboardNoticeVO updateDashboardNoticeState(
												Integer dashboardNoticeState) {

		DashboardNoticeVO vo = new DashboardNoticeVO();
		vo.setDashboardNoticeState(dashboardNoticeState);
		
		int autoGeneratedKey = dao.insert(vo);
		vo = dao.getOneByID(autoGeneratedKey);
		
		return vo;
	}

	public DashboardNoticeVO getOneByID(int dashboardNoticeID) {
		return dao.getOneByID(dashboardNoticeID);
	}
	
	public List<DashboardNoticeVO> getAll() {
		return dao.getAll();
	}
	
	public List<DashboardNoticeVO> getAllByType(int dashboardNoticeType) {
		return dao.getAllByType(dashboardNoticeType);
	}
	
	public int delete(int dashboardNoticeID) {
		return dao.delete(dashboardNoticeID);
	}

}
